### PR TITLE
messaging-accouts: Add requiredPermissions for the validator app

### PR DESCRIPTION
**Pull request by Herrie82**
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by Herrie82** [comment]
@tofee Nothing specific about permissions mentioned in the logs, just funny errors. It doesn't hurt to add these permissions in any case:

2020-06-12T13:45:16.310659Z [40.662405112] user.err imaccountvalidator [] <default-lib> LS_SOCK {"ERROR_CODE":32,"ERROR":"Broken pipe","FILE":"transport.c","LINE":1406} GLIB Error
2020-06-12T13:45:16.311050Z [40.662795387] user.err imaccountvalidator [] <default-lib> LS_TRANS_NET {"ERROR_CODE":32,"ERROR":"Broken pipe","FUNC":"_LSTransportSendComplete","FILE":"/usr/src/debug/luna-service2/3.21.2-1+gitAUTOINC+090e7f4b02-r0/git/src/libluna-service2/transport.c","LINE":1406} LUNASERVICE ERROR
2020-06-12T13:45:16.311210Z [40.662955645] user.warning LunaWebAppManager [] <default-lib> LS_QUEUE {"APP_ID":"com.palm.imaccountvalidator"} _LSTransportHandleShutdown: requeueing 1 messages for service "com.palm.imaccountvalidator"
2020-06-12T13:45:19.750037Z [44.101784085] user.err imaccountvalidator [] <default-lib> LS_SOCK {"ERROR_CODE":32,"ERROR":"Broken pipe","FILE":"transport.c","LINE":1406} GLIB Error
2020-06-12T13:45:19.751061Z [44.102808372] user.err imaccountvalidator [] <default-lib> LS_TRANS_NET {"ERROR_CODE":32,"ERROR":"Broken pipe","FUNC":"_LSTransportSendComplete","FILE":"/usr/src/debug/luna-service2/3.21.2-1+gitAUTOINC+090e7f4b02-r0/git/src/libluna-service2/transport.c","LINE":1406} LUNASERVICE ERROR

**Comment by Tofee** [comment]
I'll merge it, as you say it's an improvement anyway, but the "Broken pipe" errors usually mean a process or app or service has died unexpectedly

**Comment by Tofee** [comment]
Ah, can't merge, this is one of the few I still don't have write access :p

**Comment by Herrie82** [comment]
@tofee try again ;)

**Pull request merged**
